First PR : Coleman-back-office
InseeFr/Coleman-Back-Office pull request #1
Opened 2021-06-29 15:41 UTC by Samuel-Corcaud-KeyConsulting

2021-07-05 12:20 UTC, nicolasTurban requested changes

2021-07-05 14:21 UTC, kc-bclaudel commented on README.md
> +fr.insee.coleman.ldap.services.uri.hote=https://contacts.insee.test
done

2021-07-05 14:21 UTC, kc-bclaudel commented on src/main/java/fr/insee/coleman/api/DataLoader.java
> +					new Campaign("simpsons2021x00","Survey on the Simpsons tv show 2021", 1605909600000l, 1640995199000l));
done

2021-07-05 14:21 UTC, kc-bclaudel commented on src/main/java/fr/insee/coleman/api/controller/RestManagementMonitoringInfo.java
> +//import org.apache.velocity.exception.ResourceNotFoundException;
done

2021-07-05 14:22 UTC, kc-bclaudel commented on src/main/java/fr/insee/coleman/api/controller/RestManagementMonitoringInfo.java
> +	// Vérifier les isg que l'on peut delete ou non
done

2021-07-05 14:22 UTC, kc-bclaudel commented on src/main/java/fr/insee/coleman/api/services/UploadService.java
> +	// Checks that the ISG of an upload belong to the same campaign
done

2021-07-05 14:22 UTC, kc-bclaudel commented on src/test/java/fr/insee/coleman/api/RestAuthBasicTest.java
> +				.body("datas[0].id", equalTo("simpsons2021x00"));
done

2021-07-05 14:22 UTC, kc-bclaudel commented on src/test/java/fr/insee/coleman/api/services/ManagementMonitoringInfoServiceTest.java
> +//		Mockito.when(ueService.findByIdUe("A00000789")).thenReturn(null);
done

2021-07-05 14:22 UTC, kc-bclaudel commented on src/test/java/fr/insee/coleman/api/services/ManagementMonitoringInfoServiceTest.java
> +		//Mockito.when(ueService.findByIdUe("B00000789")).thenReturn(null);
done

2021-07-05 14:22 UTC, kc-bclaudel commented on src/test/java/fr/insee/coleman/api/services/SurveyUnitServiceTest.java
> +//	}
done

2021-07-05 14:22 UTC, kc-bclaudel commented on src/main/java/fr/insee/coleman/api/services/UploadService.java
> +		// Keeps the uploads which first ISQ belongs to the survey
done

2021-07-05 14:22 UTC, kc-bclaudel commented on src/main/java/fr/insee/coleman/api/services/SurveyUnitService.java
> +		HashSet<TypeManagementMonitoringInfo> etats = new HashSet<TypeManagementMonitoringInfo>();
done

2021-07-05 14:22 UTC, kc-bclaudel commented on src/main/java/fr/insee/coleman/api/services/ManagementMonitoringInfoService.java
> +				result.ajouterIdOk(id);
done

2021-07-05 14:22 UTC, kc-bclaudel commented on src/main/java/fr/insee/coleman/api/domain/SurveyUnit.java
> +// @EqualsAndHashCode(onlyExplicitlyIncluded = true)
done

2021-07-05 14:22 UTC, kc-bclaudel commented on src/main/java/fr/insee/coleman/api/ColemanBackOfficeApplication.java
> +        + "file:///${catalina.base}/webapps/colemanbo.properties");
done

2021-07-06 08:03 UTC, nicolasTurban requested changes

2021-07-06 08:03 UTC, nicolasTurban commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Set to 0.9.0

2021-07-06 11:47 UTC, merged